<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Country;

class CountrySeeder extends Seeder
{
    public function run(): void
    {
        $countries = [
            ['name' => 'Aruba', 'code' => 'AW'],
            ['name' => 'Afghanistan', 'code' => 'AF'],
            ['name' => 'Angola', 'code' => 'AO'],
            ['name' => 'Anguilla', 'code' => 'AI'],
            ['name' => 'Åland Islands', 'code' => 'AX'],
            ['name' => 'Albania', 'code' => 'AL'],
            ['name' => 'Andorra', 'code' => 'AD'],
            ['name' => 'United Arab Emirates', 'code' => 'AE'],
            ['name' => 'Argentina', 'code' => 'AR'],
            ['name' => 'Armenia', 'code' => 'AM'],
            ['name' => 'American Samoa', 'code' => 'AS'],
            ['name' => 'Antarctica', 'code' => 'AQ'],
            ['name' => 'French Southern Territories', 'code' => 'TF'],
            ['name' => 'Antigua and Barbuda', 'code' => 'AG'],
            ['name' => 'Australia', 'code' => 'AU'],
            ['name' => 'Austria', 'code' => 'AT'],
            ['name' => 'Azerbaijan', 'code' => 'AZ'],
            ['name' => 'Burundi', 'code' => 'BI'],
            ['name' => 'Belgium', 'code' => 'BE'],
            ['name' => 'Benin', 'code' => 'BJ'],
            ['name' => 'Burkina Faso', 'code' => 'BF'],
            ['name' => 'Bangladesh', 'code' => 'BD'],
            ['name' => 'Bulgaria', 'code' => 'BG'],
            ['name' => 'Bahrain', 'code' => 'BH'],
            ['name' => 'Bahamas', 'code' => 'BS'],
            ['name' => 'Bosnia and Herzegovina', 'code' => 'BA'],
            ['name' => 'Belarus', 'code' => 'BY'],
            ['name' => 'Belize', 'code' => 'BZ'],
            ['name' => 'Bermuda', 'code' => 'BM'],
            ['name' => 'Bolivia', 'code' => 'BO'],
            ['name' => 'Brazil', 'code' => 'BR'],
            ['name' => 'Barbados', 'code' => 'BB'],
            ['name' => 'Brunei Darussalam', 'code' => 'BN'],
            ['name' => 'Bhutan', 'code' => 'BT'],
            ['name' => 'Botswana', 'code' => 'BW'],
            ['name' => 'Central African Republic', 'code' => 'CF'],
            ['name' => 'Canada', 'code' => 'CA'],
            ['name' => 'Cocos (Keeling) Islands', 'code' => 'CC'],
            ['name' => 'Switzerland', 'code' => 'CH'],
            ['name' => 'Chile', 'code' => 'CL'],
            ['name' => 'China', 'code' => 'CN'],
            ['name' => 'Cameroon', 'code' => 'CM'],
            ['name' => 'Colombia', 'code' => 'CO'],
            ['name' => 'Comoros', 'code' => 'KM'],
            ['name' => 'Cape Verde', 'code' => 'CV'],
            ['name' => 'Costa Rica', 'code' => 'CR'],
            ['name' => 'Cuba', 'code' => 'CU'],
            ['name' => 'Cyprus', 'code' => 'CY'],
            ['name' => 'Czech Republic', 'code' => 'CZ'],
            ['name' => 'Germany', 'code' => 'DE'],
            ['name' => 'Djibouti', 'code' => 'DJ'],
            ['name' => 'Denmark', 'code' => 'DK'],
            ['name' => 'Dominica', 'code' => 'DM'],
            ['name' => 'Dominican Republic', 'code' => 'DO'],
            ['name' => 'Algeria', 'code' => 'DZ'],
            ['name' => 'Ecuador', 'code' => 'EC'],
            ['name' => 'Egypt', 'code' => 'EG'],
            ['name' => 'Eritrea', 'code' => 'ER'],
            ['name' => 'Spain', 'code' => 'ES'],
            ['name' => 'Estonia', 'code' => 'EE'],
            ['name' => 'Ethiopia', 'code' => 'ET'],
            ['name' => 'Finland', 'code' => 'FI'],
            ['name' => 'Fiji', 'code' => 'FJ'],
            ['name' => 'France', 'code' => 'FR'],
            ['name' => 'Gabon', 'code' => 'GA'],
            ['name' => 'United Kingdom', 'code' => 'GB'],
            ['name' => 'Grenada', 'code' => 'GD'],
            ['name' => 'Georgia', 'code' => 'GE'],
            ['name' => 'Ghana', 'code' => 'GH'],
            ['name' => 'Gambia', 'code' => 'GM'],
            ['name' => 'Guinea', 'code' => 'GN'],
            ['name' => 'Greece', 'code' => 'GR'],
            ['name' => 'Guatemala', 'code' => 'GT'],
            ['name' => 'Guinea-Bissau', 'code' => 'GW'],
            ['name' => 'Guyana', 'code' => 'GY'],
            ['name' => 'Hong Kong', 'code' => 'HK'],
            ['name' => 'Honduras', 'code' => 'HN'],
            ['name' => 'Croatia', 'code' => 'HR'],
            ['name' => 'Haiti', 'code' => 'HT'],
            ['name' => 'Hungary', 'code' => 'HU'],
            ['name' => 'Indonesia', 'code' => 'ID'],
            ['name' => 'Ireland', 'code' => 'IE'],
            ['name' => 'Israel', 'code' => 'IL'],
            ['name' => 'India', 'code' => 'IN'],
            ['name' => 'Iraq', 'code' => 'IQ'],
            ['name' => 'Iran', 'code' => 'IR'],
            ['name' => 'Iceland', 'code' => 'IS'],
            ['name' => 'Italy', 'code' => 'IT'],
            ['name' => 'Jamaica', 'code' => 'JM'],
            ['name' => 'Jordan', 'code' => 'JO'],
            ['name' => 'Japan', 'code' => 'JP'],
            ['name' => 'Kenya', 'code' => 'KE'],
            ['name' => 'Cambodia', 'code' => 'KH'],
            ['name' => 'South Korea', 'code' => 'KR'],
            ['name' => 'Kuwait', 'code' => 'KW'],
            ['name' => 'Kazakhstan', 'code' => 'KZ'],
            ['name' => 'Laos', 'code' => 'LA'],
            ['name' => 'Lebanon', 'code' => 'LB'],
            ['name' => 'Sri Lanka', 'code' => 'LK'],
            ['name' => 'Lithuania', 'code' => 'LT'],
            ['name' => 'Luxembourg', 'code' => 'LU'],
            ['name' => 'Latvia', 'code' => 'LV'],
            ['name' => 'Morocco', 'code' => 'MA'],
            ['name' => 'Monaco', 'code' => 'MC'],
            ['name' => 'Moldova', 'code' => 'MD'],
            ['name' => 'Madagascar', 'code' => 'MG'],
            ['name' => 'Mexico', 'code' => 'MX'],
            ['name' => 'Malaysia', 'code' => 'MY'],
            ['name' => 'Mozambique', 'code' => 'MZ'],
            ['name' => 'Namibia', 'code' => 'NA'],
            ['name' => 'Niger', 'code' => 'NE'],
            ['name' => 'Nigeria', 'code' => 'NG'],
            ['name' => 'Netherlands', 'code' => 'NL'],
            ['name' => 'Norway', 'code' => 'NO'],
            ['name' => 'Nepal', 'code' => 'NP'],
            ['name' => 'New Zealand', 'code' => 'NZ'],
            ['name' => 'Oman', 'code' => 'OM'],
            ['name' => 'Panama', 'code' => 'PA'],
            ['name' => 'Peru', 'code' => 'PE'],
            ['name' => 'Philippines', 'code' => 'PH'],
            ['name' => 'Pakistan', 'code' => 'PK'],
            ['name' => 'Poland', 'code' => 'PL'],
            ['name' => 'Portugal', 'code' => 'PT'],
            ['name' => 'Paraguay', 'code' => 'PY'],
            ['name' => 'Qatar', 'code' => 'QA'],
            ['name' => 'Romania', 'code' => 'RO'],
            ['name' => 'Russia', 'code' => 'RU'],
            ['name' => 'Rwanda', 'code' => 'RW'],
            ['name' => 'Saudi Arabia', 'code' => 'SA'],
            ['name' => 'Sweden', 'code' => 'SE'],
            ['name' => 'Singapore', 'code' => 'SG'],
            ['name' => 'Slovenia', 'code' => 'SI'],
            ['name' => 'Slovakia', 'code' => 'SK'],
            ['name' => 'Senegal', 'code' => 'SN'],
            ['name' => 'Somalia', 'code' => 'SO'],
            ['name' => 'Suriname', 'code' => 'SR'],
            ['name' => 'South Sudan', 'code' => 'SS'],
            ['name' => 'El Salvador', 'code' => 'SV'],
            ['name' => 'Syria', 'code' => 'SY'],
            ['name' => 'Thailand', 'code' => 'TH'],
            ['name' => 'Togo', 'code' => 'TG'],
            ['name' => 'Trinidad and Tobago', 'code' => 'TT'],
            ['name' => 'Tunisia', 'code' => 'TN'],
            ['name' => 'Turkey', 'code' => 'TR'],
            ['name' => 'Taiwan', 'code' => 'TW'],
            ['name' => 'Tanzania', 'code' => 'TZ'],
            ['name' => 'Ukraine', 'code' => 'UA'],
            ['name' => 'Uganda', 'code' => 'UG'],
            ['name' => 'United States of America', 'code' => 'US'],
            ['name' => 'Uruguay', 'code' => 'UY'],
            ['name' => 'Uzbekistan', 'code' => 'UZ'],
            ['name' => 'Venezuela', 'code' => 'VE'],
            ['name' => 'Vietnam', 'code' => 'VN'],
            ['name' => 'South Africa', 'code' => 'ZA'],
            ['name' => 'Zimbabwe', 'code' => 'ZW'],
        ];

        foreach ($countries as $country) {
            Country::updateOrCreate(
                ['name' => $country['name']],
                ['code' => $country['code']]
            );
        }
    }
}
